module.exports = {
  mode: 'jit',
  purge: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  darkMode: false,
  theme: {
    extend: {
      colors: {
        primary: '#00E7F9',
        secondary: '#8257E6',
        black: '#000000',
        'dark-gray': '#0D0D0D',
        gray: '#494949',
        'light-gray': '#B5B5B5',
        white: '#FAFAFA',
      },
      fontFamily: {
        sans: ['Arial', 'sans-serif'],
        poppins: ['Poppins', 'sans-serif'],
      },
      fontSize: {
        'xs': '12px',
        'sm': '14px',
        'base': '16px',
        'lg': '18px',
        'xl': '20px',
        '2xl': '24px',
        '3xl': '30px',
        '4xl': '36px',
        '5xl': '48px',
        '6xl': '64px',
        '7xl': '80px',
        'tagline': '75px',
        'section': '33.18px',
        'button': '13.33px',
        'card': '19.2px',
      },
      fontWeight: {
        'regular': 400,
        'bold': 700,
      },
      lineHeight: {
        'none': 1,
        'tight': 1.25,
        'snug': 1.375,
        'normal': 1.5,
        'relaxed': 1.625,
        'loose': 2,
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
